### ISSUE TITLE
Run on a ST Nucleo board (for when you don't have a Neotron Pico handy)

### ISSUE THREAD

**Issue by jonathanpallant** [Neotron-Compute/Neotron-BMC#19]
We should have a feature for running on a Nucleo board, seeing as we can't make Neotron PCBs until a bunch more parts come into stock. It also rules out issues with my bad PCB design.

The main difference is the Nucleo has a crystal fitted to PF0/PF1 so the button inputs might not work. But if the Crystal oscillator isn't enabled, maybe each end of the crystal won't mind being grounded with a button input. Or you could live without buttons. Or live without something else instead.

**Comment by jonathanpallant** [comment]
Hmm. They are all totally out of stock. https://uk.rs-online.com/web/p/microcontroller-development-tools/7587554 might work better.

**Comment by thejpster** [comment]
OK, we're going with a Nucleo-64 carrying an STM32F401 because @Dajamante has one to hand.

**Comment by Dajamante** [comment]
Shall we close this one then?

**Comment by thejpster** [comment]
It doesn't run on an F401 yet ;)
